#!/usr/bin/env python
"""
Script to create a web application on this server. Call this like so:
    $ create -b develop appname 
"""
import sys
from optparse import OptionParser
from renga.apps import WebApplication

def main():

    usage = "usage: %prog [options] <appname>"
    parser = OptionParser(usage)
    parser.add_option("-b", "--branch", default="master", help="Specify branch to use for deployment. [default]=master")
    parser.add_option("-s", "--staging", action="store_true", help="Use the develop branch of the app.")
    (options, args) = parser.parse_args()

    if len(args) != 1:
        parser.error("Specify exactly 1 argument, %d given." % len(args))

    if options.staging:
        options.branch = "develop"

    app = WebApplication(args[0], branch=options.branch)
    app.webserver_start()

if __name__ == "__main__":
    main()